---
title: "Proposed Rules Open for Comment"
#author: "Devin Judge-Lord"
output:
    html_document:
      highlight: zenburn
      toc: false
      toc_float: true
      #code_folding: hide
editor_options: 
  chunk_output_type: console
---

as of 10-13-2021

```{r global.options, include=FALSE}
source(here::here("setup.R"))


knitr::opts_chunk$set(echo = FALSE, 
                      cache = FALSE)

library(kableExtra)
kablebox <- . %>% 
  head(1000) %>% 
  knitr::kable(digits = 3) %>% 
  kable_styling() %>% 
  scroll_box(height = "400px")
```


```{r}

# a function to clean raw selected text
clean_summary <- . %>% 
  str_remove_all("./em../mark.|.mark..em.") %>%
  str_replace_all("\\&hellip;\\&nbsp;"," ") %>% 
  str_replace_all("[^[A-z][0-9] \\.\\,\\?\\!\\;&\\;<>]", " ") %>% 
  str_remove_all("\\(|\\)|\\[|\\]") %>%
  str_squish() %>%
  str_remove_all("`") %>%
  str_squish()

load(here("data", "ejPRnew.Rdata"))

ej_open <- ejPRnew %>% 
  #filter(open_for_comment) %>% 
    select(-last_modified_date) %>% 
  mutate(EJ = highlighted_content %>% clean_summary() ) %>% 
  select(-highlighted_content, -lastpage, -type, -links) %>% 
  arrange(rev(open_for_comment)) 

load(here("data", "climatePR.Rdata"))

climate_open <- climatePR %>% 
  #filter(open_for_comment)%>% 
  mutate(Climate = highlighted_content %>% clean_summary() )%>% 
  select(-highlighted_content, -lastpage, -type, -links, -last_modified_date) %>% 
  arrange(rev(open_for_comment)) 

open <- full_join(ej_open, climate_open) %>% 
  mutate(Notes = "", Open = open_for_comment) %>% 
  filter(comment_start_date > as.Date("2021-01-17")) %>% 
  arrange(rev(as.Date(comment_end_date))) %>% 
  mutate(open_for_comment = as.numeric(open_for_comment)) %>% 
  arrange(-open_for_comment)

# clean up for presentation
o <- open %>% 
    mutate(`Proposed Rule` = str_c("Comments due ", 
                                   comment_end_date %>% 
                                     str_remove("T.*") %>% 
                                     replace_na("?"), " on ", title,
                                   "\n https://www.regulations.gov/document/", id, 
                                   "\n \n https://www.federalregister.gov/d/", fr_doc_num) ) %>%
    select(`Proposed Rule`, EJ, Climate, Open, Notes) 
```

```{r googlesheet, eval= FALSE}
library(googlesheets4)
gs4_auth()
1
1

write_sheet(open, ss = "1Owte4nR18J92xxnPaTDnGgRALZm3-rScCe_co_ohuDU", sheet = "raw")

write_sheet(o, ss = "1Owte4nR18J92xxnPaTDnGgRALZm3-rScCe_co_ohuDU", sheet = "formatted")
```

```{r comments, eval=FALSE}

load(here("data", "ejcommentsnew.Rdata"))

ejcomments_open <- ejcommentsnew %>% 
  mutate(docket_id = str_remove(id, "-[0-9]*")) %>%
  filter(docket_id %in% open$docket_id) %>% 
  mutate(URL= str_c(title, " https://www.regulations.gov/document/", id)) %>%
  select(URL, EJ = highlighted_content)

load(here("data", "climatecomments.Rdata"))

climatecomments_open <- climatecomments %>% 
  mutate(docket_id = str_remove(id, "-[0-9]*")) %>%
  filter(docket_id %in% open$docket_id) %>% 
  mutate(URL= str_c(title, " https://www.regulations.gov/document/", id)) %>%
  select(URL, Climate = highlighted_content)
```

### Mentioning "Environmental Justice" and "Climate Change"

```{r}
o %>% drop_na(EJ, Climate) %>% kablebox()
```

### Mentioning "Environmental Justice" but not "Climate Change"

```{r}
o %>% filter(is.na(Climate)) %>% select(-Climate) %>% kablebox()
```

### Mentioning "Climate Change" but not ""Environmental Justice"

```{r}
o %>% filter(is.na(EJ)) %>% select(-EJ) %>% kablebox()
```

### Raw data [here](https://docs.google.com/spreadsheets/d/1Owte4nR18J92xxnPaTDnGgRALZm3-rScCe_co_ohuDU/edit?usp=sharing) {-}